### ISSUE TITLE
External Boot Camp Volumes

### ISSUE THREAD

**Issue by laposheureux** [mikew/vmware-fusion-bootcamp#1]
Just a note if you want to add it to your readme, if anyone comes across this and is running into the same troubles but is using an external drive...this script works great as long as you point it to the correct disk number and this hard codes disk0 (mine was disk2) in two places that would need to be changed based on data from `diskutil list`

**Comment by mikew** [comment]
Glad to hear that worked. Shouldn't be difficult to add the disk as an argument to the script.
